@startuml
'https://plantuml.com/sequence-diagram

autonumber

ReferenceDataController -> ReferenceDataAggregatorService: getReferenceDataByCode Ex: ["category", "sub-category"]

ReferenceDataAggregatorService -> CategoryService: getReferenceData
CategoryService -> ReferenceDataAggregatorService: List<ReferenceDataElement>

ReferenceDataAggregatorService -> SubCategoryService: getReferenceData
SubCategoryService -> ReferenceDataAggregatorService: List<ReferenceDataElement>


ReferenceDataAggregatorService --> ReferenceDataController: Response: List<ReferenceData>


@enduml